
version: "3.9"

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local
  grafana-data:
    driver: local
  prometheus-data:
    driver: local

networks:
  postgres:
    driver: bridge
    external: false

services:

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:mainline-alpine3.18-slim
    volumes:
      - ./volumes/data/nginx/log:/var/log/nginx
      - ./volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/etc/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./volumes/etc/nginx/ssl:/etc/nginx/ssl:ro
      - ./public:/var/www/1h
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Zxcv7890"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "./volumes/etc/postgres/init:/docker-entrypoint-initdb.d"
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: always
    networks:
      - postgres

  pgadmin:
    container_name: pgadmins
    image: dpage/pgadmin4:latest
    environment:
      environment:
      PGADMIN_DEFAULT_EMAIL: "your-email@example.com"
      PGADMIN_DEFAULT_PASSWORD: "yourpassword"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'strongpassword'  # Замените на ваш пароль
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SERVER_HTTP_PORT: '4000'  # Указываем Grafana использовать порт 4000
    ports:
      - "4000:4000"  # Пробрасываем порт 4000
    restart: unless-stopped
    networks:
      - postgres

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      #- /home/o.boldyrev/1sh/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: unless-stopped
    networks:
      - postgres

  firstappone:
    container_name: firstappone
    image: firstappone:latest

    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - postgres
