global:
  scrape_interval: 15s # По умолчанию Prometheus скрейпит метрики каждые 15 секунд

scrape_configs:
  - job_name: 'fastapi'
    scrape_interval: 5s # Частота сбора метрик для этой задачи
    static_configs:
      - targets: ['localhost:8000'] # Список адресов приложений, которые Prometheus будет мониторить
